apiVersion: v1
kind: Secret

metadata:
  name: jwt-secret
  namespace: ${K8S_NAMESPACE}

type: Opaque

stringData:
  JWT_SECRET: "${JWT_SECRET}"
  JWT_PRIVATE_KEY: "${JWT_PRIVATE_KEY}"
  JWT_PUBLIC_KEY: "${JWT_PUBLIC_KEY}"
  JWT_ACTIVE_KID: "${JWT_ACTIVE_KID}"
  JWT_ISSUER: "${JWT_ISSUER}"
  JWT_AUDIENCE: "${JWT_AUDIENCE}"
  JWT_ALGORITHM: "${JWT_ALGORITHM}"
  JWT_ACCESS_TOKEN_EXPIRES_MINUTES: "${JWT_ACCESS_TOKEN_EXPIRES_MINUTES}"
  JWT_REFRESH_TOKEN_EXPIRES_DAYS: "${JWT_REFRESH_TOKEN_EXPIRES_DAYS}"
  JWT_REFRESH_TOKEN_SECRET: "${JWT_REFRESH_TOKEN_SECRET}"
  JWT_SESSION_SECRET: "${JWT_SESSION_SECRET}"
  JWT_EXPIRATION_MINUTES: "${JWT_EXPIRATION_MINUTES}"
