apiVersion: v1

kind: Secret

metadata:
  name: mongodb-secret
  namespace: ${K8S_NAMESPACE}

type: Opaque

stringData:
  MONGO_HOST: ${MONGO_HOST}
  MONGO_PORT: ${MONGO_PORT}
  MONGO_DATABASE: ${MONGO_DATABASE}
  MONGO_USERNAME: ${MONGO_USERNAME}
  MONGO_PASSWORD: ${MONGO_PASSWORD}
  MONGO_AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
  MONGO_URI: ${MONGO_URI}