apiVersion: v1

kind: Secret

metadata:
  name: mongodb-secret
  namespace: video-converter

type: Opaque

stringData:

  MONGO_INITDB_ROOT_USERNAME: admin

  MONGO_INITDB_ROOT_PASSWORD: password123

  MONGODB_URI: mongodb://admin:password123@mongodb:27017