apiVersion: v1
kind: Secret

metadata:
  name: notification-secret
  namespace: ${K8S_NAMESPACE}

type: Opaque

stringData:
  SMTP_USERNAME: "${SMTP_USERNAME}"
  SMTP_PASSWORD: "${SMTP_PASSWORD}"
  SMTP_EMAIL: "${SMTP_EMAIL}"
  JWT_SECRET: "${JWT_SECRET}"
