apiVersion: v1

kind: Secret

metadata:
  name: postgres-secret
  namespace: video-converter

type: Opaque

stringData:

  POSTGRES_USER: postgres

  POSTGRES_PASSWORD: password123

  POSTGRES_DB: video_converter_db

  DATABASE_URL: postgresql://postgres:password123@postgresql:5432/video_converter_db