apiVersion: v1
kind: Secret

metadata:
  name: rabbitmq-secret
  namespace: ${K8S_NAMESPACE}

type: Opaque

stringData:

  # =========================================================
  # RABBITMQ AUTHENTICATION
  # =========================================================

  RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}

  RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}

  RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}

  # =========================================================
  # RABBITMQ SECURITY
  # =========================================================

  RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}

  # =========================================================
  # RABBITMQ CONNECTION URIS
  # =========================================================

  RABBITMQ_AMQP_URL: ${RABBITMQ_AMQP_URL}

  RABBITMQ_URI: ${RABBITMQ_URI}
---
apiVersion: v1
