apiVersion: v1
kind: ConfigMap

metadata:
  name: gateway-config
  namespace: ${K8S_NAMESPACE}

data:

  APP_NAME: "gateway-service"

  APP_ENV: "${APP_ENV}"

  APP_PORT: "${GATEWAY_PORT}"

  LOG_LEVEL: "${LOG_LEVEL}"

  API_PREFIX: "${API_PREFIX}"

  FRONTEND_URL: "${FRONTEND_URL}"

  CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"

  AUTH_SERVICE_HOST: "${AUTH_SERVICE_HOST}"

  AUTH_SERVICE_PORT: "${AUTH_SERVICE_PORT}"

  CONVERTER_SERVICE_HOST: "${CONVERTER_SERVICE_HOST}"

  CONVERTER_SERVICE_PORT: "${CONVERTER_SERVICE_PORT}"

  NOTIFICATION_SERVICE_HOST: "${NOTIFICATION_SERVICE_HOST}"

  NOTIFICATION_SERVICE_PORT: "${NOTIFICATION_SERVICE_PORT}"

  MONGO_HOST: "${MONGO_HOST}"

  MONGO_PORT: "${MONGO_PORT}"

  MONGO_DATABASE: "${MONGO_DATABASE}"

  POSTGRES_HOST: "${POSTGRES_HOST}"

  POSTGRES_PORT: "${POSTGRES_PORT}"

  POSTGRES_DB: "${POSTGRES_DB}"

  RABBITMQ_HOST: "${RABBITMQ_HOST}"

  RABBITMQ_PORT: "${RABBITMQ_PORT}"

  VIDEO_UPLOAD_QUEUE: "${VIDEO_UPLOAD_QUEUE}"

  VIDEO_UPLOAD_RETRY_QUEUE: "${VIDEO_UPLOAD_RETRY_QUEUE}"

  VIDEO_UPLOAD_DLQ: "${VIDEO_UPLOAD_DLQ}"

  NOTIFICATION_QUEUE: "${NOTIFICATION_QUEUE}"

  EMAIL_QUEUE: "${EMAIL_QUEUE}"

  AWS_REGION: "${AWS_REGION}"

  AWS_S3_BUCKET: "${AWS_S3_BUCKET}"

  AWS_S3_AUDIO_BUCKET: "${AWS_S3_AUDIO_BUCKET}"

  AWS_S3_VIDEO_BUCKET: "${AWS_S3_VIDEO_BUCKET}"

  JWT_ALGORITHM: "${JWT_ALGORITHM}"

  JWT_ISSUER: "${JWT_ISSUER}"

  JWT_AUDIENCE: "${JWT_AUDIENCE}"

  ACCESS_TOKEN_EXPIRE_MINUTES: "${JWT_ACCESS_TOKEN_EXPIRES_MINUTES}"

  REFRESH_TOKEN_EXPIRE_DAYS: "${REFRESH_TOKEN_EXPIRE_DAYS}"

  MAX_VIDEO_UPLOAD_SIZE_MB: "${MAX_VIDEO_UPLOAD_SIZE_MB}"

  WEBSOCKET_HOST: "${WEBSOCKET_HOST}"

  WEBSOCKET_PORT: "${WEBSOCKET_PORT}"
