apiVersion: v1
kind: ConfigMap

metadata:
  name: gateway-config
  namespace: ${K8S_NAMESPACE}

data:
  APP_NAME: "${GATEWAY_APP_NAME}"

  APP_ENV: "${APP_ENV}"

  APP_PORT: "${GATEWAY_PORT}"

  JWT_AUTH_SERVICE_URL: "${JWT_AUTH_SERVICE_URL}"

  CONVERTER_SERVICE_URL: "${CONVERTER_SERVICE_URL}"

  NOTIFICATION_SERVICE_URL: "${NOTIFICATION_SERVICE_URL}"

  JWT_ALGORITHM: "${JWT_ALGORITHM}"

  LOG_LEVEL: "${LOG_LEVEL}"