apiVersion: v1
kind: ConfigMap

metadata:
  name: gateway-config
  namespace: ${K8S_NAMESPACE}

data:
  APP_NAME: "${GATEWAY_APP_NAME}"
  APP_ENV: "${APP_ENV}"
  APP_PORT: "${GATEWAY_PORT}"
  LOG_LEVEL: "${LOG_LEVEL}"
  JWT_AUTH_SERVICE_URL: "${JWT_AUTH_SERVICE_URL}"
  CONVERTER_SERVICE_URL: "${CONVERTER_SERVICE_URL}"
  NOTIFICATION_SERVICE_URL: "${NOTIFICATION_SERVICE_URL}"
  JWT_ALGORITHM: "${JWT_ALGORITHM}"
  AUTH_SERVICE_HOST: "${AUTH_SERVICE_HOST}"
  AUTH_SERVICE_PORT: "${AUTH_SERVICE_PORT}"
  CONVERTER_SERVICE_HOST: "${CONVERTER_SERVICE_HOST}"
  CONVERTER_SERVICE_PORT: "${CONVERTER_SERVICE_PORT}"
  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT}"
  RABBITMQ_EXCHANGE: "${RABBITMQ_EXCHANGE}"
  VIDEO_UPLOAD_QUEUE: "${VIDEO_UPLOAD_QUEUE}"
  NOTIFICATION_QUEUE: "${NOTIFICATION_QUEUE}"
  GATEWAY_EVENTS_QUEUE: "${GATEWAY_EVENTS_QUEUE}"
  AWS_REGION: "${AWS_REGION}"
  S3_UPLOAD_BUCKET: "${S3_UPLOAD_BUCKET}"
  S3_AUDIO_BUCKET: "${S3_AUDIO_BUCKET}"
  CORS_ALLOWED_ORIGINS: "${CORS_ALLOWED_ORIGINS}"
  FRONTEND_URL: "${FRONTEND_URL}"
