apiVersion: networking.k8s.io/v1

kind: Ingress

metadata:
  name: gateway-ingress
  namespace: video-converter

  annotations:
    kubernetes.io/ingress.class: nginx

spec:

  rules:

    - host: video-converter.local

      http:

        paths:

          - path: /

            pathType: Prefix

            backend:

              service:
                name: gateway-service

                port:
                  number: 80