apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: ${KEDA_TRIGGER_AUTH_NAME}
  namespace: ${K8S_NAMESPACE}
spec:
  secretTargetRef:
    - parameter: host
      name: rabbitmq-secret
      key: KEDA_RABBITMQ_HOST
