apiVersion: v1

kind: ConfigMap

metadata:
  name: notification-config
  namespace: video-converter

data:

  APP_NAME: "notification-service"

  APP_ENV: "production"

  APP_PORT: "8003"

  RABBITMQ_HOST: "rabbitmq"

  RABBITMQ_PORT: "5672"

  SMTP_HOST: "smtp.gmail.com"

  SMTP_PORT: "587"

  WEBSOCKET_HOST: "0.0.0.0"

  WEBSOCKET_PORT: "8765"