apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-config
  namespace: ${K8S_NAMESPACE}

data:
  APP_NAME: "${APP_NAME}"

  APP_ENV: "${APP_ENV}"

  APP_PORT: "${APP_PORT}"

  RABBITMQ_HOST: "${RABBITMQ_HOST}"

  RABBITMQ_PORT: "${RABBITMQ_PORT}"

  SMTP_HOST: "${SMTP_HOST}"

  SMTP_PORT: "${SMTP_PORT}"

  WEBSOCKET_HOST: "${WEBSOCKET_HOST}"

  WEBSOCKET_PORT: "${WEBSOCKET_PORT}"
