apiVersion: v1
kind: ConfigMap

metadata:
  name: notification-config
  namespace: ${K8S_NAMESPACE}

data:
  APP_NAME: "${APP_NAME}"

  APP_ENV: "${APP_ENV}"

  APP_PORT: "${APP_PORT}"

  RABBITMQ_HOST: "${RABBITMQ_HOST}"

  RABBITMQ_PORT: "${RABBITMQ_PORT}"

  SMTP_HOST: "${SMTP_HOST}"

  SMTP_PORT: "${SMTP_PORT}"

  WEBSOCKET_HOST: "${WEBSOCKET_HOST}"

  SMTP_FROM_EMAIL: "${SMTP_FROM_EMAIL}"

  NOTIFICATION_QUEUE: "${NOTIFICATION_QUEUE}"

  EMAIL_QUEUE: "${EMAIL_QUEUE}"

  RABBITMQ_EXCHANGE: "${RABBITMQ_EXCHANGE}"

  RABBITMQ_ROUTING_KEY: "${RABBITMQ_ROUTING_KEY}"

  FRONTEND_URL: "${FRONTEND_URL}"

  API_BASE_URL: "${API_BASE_URL}"

  EMAIL_ENABLED: "${EMAIL_ENABLED}"

  WEBSOCKET_NOTIFICATIONS_ENABLED: "${WEBSOCKET_NOTIFICATIONS_ENABLED}"

  HEALTHCHECK_PATH: "${HEALTHCHECK_PATH}"
