apiVersion: v1

kind: Service

metadata:
  name: notification-service
  namespace: ${K8S_NAMESPACE}

spec:

  selector:
    app: notification

  ports:

    - protocol: TCP
      port: 80
      targetPort: 8003

  type: ClusterIP