apiVersion: v1
kind: Namespace
metadata:
  name: ${APP_NAMESPACE}

---
apiVersion: v1
kind: Namespace
metadata:
  name: ${DATABASE_NAMESPACE}

---
apiVersion: v1
kind: Namespace
metadata:
  name: ${MESSAGING_NAMESPACE}

---
apiVersion: v1
kind: Namespace
metadata:
  name: ${MONITORING_NAMESPACE}

---
apiVersion: v1
kind: Namespace
metadata:
  name: ${INGRESS_NAMESPACE}

---
apiVersion: v1
kind: Namespace
metadata:
  name: ${JENKINS_NAMESPACE}
