apiVersion: v1

kind: PersistentVolume

metadata:
  name: shared-storage-pv

spec:

  capacity:
    storage: 20Gi

  accessModes:
    - ReadWriteOnce

  storageClassName: video-storage-class

  persistentVolumeReclaimPolicy: Delete

  csi:

    driver: ebs.csi.aws.com

    volumeHandle: vol-xxxxxxxxxxxxxxxxx

    fsType: ext4