apiVersion: v1

kind: PersistentVolumeClaim

metadata:
  name: ${SHARED_STORAGE_PVC_NAME}
  namespace: ${K8S_NAMESPACE}

spec:

  accessModes:
    - ReadWriteOnce

  storageClassName: ${STORAGE_CLASS_NAME}

  resources:

    requests:
      storage: ${SHARED_STORAGE_SIZE}