apiVersion: storage.k8s.io/v1

kind: StorageClass

metadata:
  name: video-storage-class

provisioner: ebs.csi.aws.com

volumeBindingMode: WaitForFirstConsumer

parameters:
  type: gp3

reclaimPolicy: Delete

allowVolumeExpansion: true
