apiVersion: v1
kind: ServiceAccount

metadata:
name: converter-service-account
namespace: ${K8S_NAMESPACE}

annotations:
eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${APP_NAME}-${APP_ENV}-converter-irsa-role
