apiVersion: v1
kind: ServiceAccount

metadata:
  name: worker-service-account
  namespace: ${K8S_NAMESPACE}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/${PROJECT_NAME}-${APP_ENV}-worker-irsa-role
