import os

VIDEO_UPLOAD_QUEUE = os.getenv("VIDEO_UPLOAD_QUEUE")

VIDEO_UPLOAD_RETRY_QUEUE = os.getenv("VIDEO_UPLOAD_RETRY_QUEUE")

VIDEO_UPLOAD_DLQ = os.getenv("VIDEO_UPLOAD_DLQ")

NOTIFICATION_QUEUE = os.getenv("NOTIFICATION_QUEUE")

EMAIL_QUEUE = os.getenv("EMAIL_QUEUE")