apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:
  name: mongodb-network-policy
  namespace: ${DATABASE_NAMESPACE}

spec:
  podSelector:
    matchLabels:
      app: ${MONGODB_APP_NAME}

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ${K8S_NAMESPACE}
          podSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - ${CONVERTER_APP_NAME}
                  - ${GATEWAY_POD_LABEL}
                  - ${GATEWAY_WORKER_POD_LABEL}

      ports:
        - protocol: TCP
          port: ${MONGODB_PORT}
