apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:
  name: mongodb-network-policy
  namespace: ${DATABASE_NAMESPACE}

spec:
  podSelector:
    matchLabels:
      app: ${MONGODB_APP_NAME}

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ${K8S_NAMESPACE}
          podSelector:
            matchLabels:
              app: ${CONVERTER_APP_NAME}

      ports:
        - protocol: TCP
          port: ${MONGODB_PORT}
