apiVersion: networking.k8s.io/v1

kind: NetworkPolicy

metadata:
  name: postgres-network-policy
  namespace: ${DATABASE_NAMESPACE}

spec:
  podSelector:
    matchLabels:
      app: ${POSTGRES_APP_NAME}

  policyTypes:
    - Ingress

  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ${K8S_NAMESPACE}
          podSelector:
            matchLabels:
              app: auth-service

      ports:
        - protocol: TCP
          port: ${POSTGRES_PORT}
