apiVersion: v1
kind: Secret

metadata:

  name: mongodb-secret

  namespace: {{ .Release.Namespace }}

type: Opaque

stringData:

  MONGO_USERNAME: ${MONGO_USERNAME}

  MONGO_PASSWORD: ${MONGO_PASSWORD}

  MONGO_DATABASE: ${MONGO_DATABASE}