apiVersion: v1

kind: Secret

metadata:
name: rabbitmq-secret

type: Opaque

stringData:

rabbitmq-username: "${RABBITMQ_USERNAME}"

rabbitmq-password: {{ required "RabbitMQ password must be set" .Values.RABBITMQ_PASSWORD | b64enc }}

rabbitmq-erlang-cookie: "${RABBITMQ_ERLANG_COOKIE}"
