apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
stringData:
  rabbitmq-username: "{{ .Values.RABBITMQ_USERNAME | default "guest" }}"
  rabbitmq-password: {{ required "RabbitMQ password must be set" .Values.RABBITMQ_PASSWORD | quote }}
  rabbitmq-erlang-cookie: "{{ .Values.RABBITMQ_ERLANG_COOKIE | default "local-dev-cookie" }}"
