apiVersion: v1
kind: Service
metadata:
  name: rabbitmq

spec:
  selector:
    app: rabbitmq

  ports:
    - name: amqp
      protocol: TCP
      port: {{ .Values.service.amqpPort }}
      targetPort: 5672

    - name: management
      protocol: TCP
      port: {{ .Values.service.managementPort }}
      targetPort: 15672

  type: {{ .Values.service.type }}