apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:
  name: ${GATEWAY_SERVICE_MONITOR_NAME}
  namespace: ${MONITORING_NAMESPACE}
  labels:
    release: ${PROMETHEUS_RELEASE_NAME}

spec:
  selector:
    matchLabels:
      app: ${GATEWAY_APP_LABEL}

  namespaceSelector:
    matchNames:
      - ${APPLICATION_NAMESPACE}

  endpoints:
    - port: ${GATEWAY_METRICS_PORT_NAME}
      path: ${GATEWAY_METRICS_PATH}
      interval: ${PROMETHEUS_SCRAPE_INTERVAL}
