apiVersion: monitoring.coreos.com/v1

kind: ServiceMonitor

metadata:

  name: ${NOTIFICATION_SERVICE_MONITOR_NAME}

  namespace: ${MONITORING_NAMESPACE}

spec:

  selector:

    matchLabels:

      app: ${NOTIFICATION_APP_LABEL}

  namespaceSelector:

    matchNames:

      - ${APPLICATION_NAMESPACE}

  endpoints:

    - port: ${NOTIFICATION_METRICS_PORT_NAME}

      path: ${NOTIFICATION_METRICS_PATH}

      interval: ${NOTIFICATION_METRICS_INTERVAL}