apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: ${K8S_NAMESPACE}
  labels:
    app: prometheus
    environment: ${APP_ENV}
data:
  prometheus.yml: |
    global:
      scrape_interval: 30s
    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ["localhost:9090"]
