apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PROMETHEUS_PVC_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app: prometheus
    service: prometheus-service
    environment: ${APP_ENV}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ${PROMETHEUS_STORAGE_CLASS}
  resources:
    requests:
      storage: ${PROMETHEUS_STORAGE_SIZE}
