#!/bin/bash
# Canonical environment variable aliases.
# Source this before deploy, terraform, or local docker-compose runs so
# GitHub variable names map to names expected by application code and K8s.

set -euo pipefail

_ENV_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="${ROOT_DIR:-$(cd "${_ENV_LIB_DIR}/../.." && pwd)}"

_first_nonempty() {
  local value
  for key in "$@"; do
    value="${!key:-}"
    if [ -n "$value" ]; then
      printf '%s' "$value"
      return 0
    fi
  done
  return 1
}

_export_alias() {
  local target="$1"
  shift
  local resolved
  if resolved="$(_first_nonempty "$@")"; then
    export "${target}=${resolved}"
  fi
}

# Docker
_export_alias DOCKER_USERNAME DOCKER_USERNAME
_export_alias DOCKER_REGISTRY DOCKER_REGISTRY DOCKER_IMAGE_REGISTRY

# Derive JWT public key from private key when missing
if [ -z "${JWT_PUBLIC_KEY:-}" ] && [ -n "${JWT_PRIVATE_KEY:-}" ]; then
  JWT_PUBLIC_KEY="$(printf '%s' "$JWT_PRIVATE_KEY" | openssl rsa -pubout 2>/dev/null || true)"
  export JWT_PUBLIC_KEY
fi
if [ -z "${JWT_PUBLIC_KEY:-}" ] && [ -f "${ROOT_DIR}/jwt-private.pem" ]; then
  JWT_PUBLIC_KEY="$(openssl rsa -in "${ROOT_DIR}/jwt-private.pem" -pubout 2>/dev/null || true)"
  export JWT_PUBLIC_KEY
fi

# JWT — accept both legacy TOKEN_* and current names
_export_alias JWT_ISSUER JWT_ISSUER JWT_TOKEN_ISSUER
_export_alias JWT_AUDIENCE JWT_AUDIENCE JWT_TOKEN_AUDIENCE
_export_alias JWT_ALGORITHM JWT_ALGORITHM
if [ -n "${JWT_PRIVATE_KEY:-}" ] || [ -f "${ROOT_DIR}/jwt-private.pem" ]; then
  export JWT_ALGORITHM="RS256"
else
  export JWT_ALGORITHM="${JWT_ALGORITHM:-RS256}"
fi
_export_alias JWT_ACTIVE_KID JWT_ACTIVE_KID
export JWT_ACTIVE_KID="${JWT_ACTIVE_KID:-default}"
_export_alias JWT_ACCESS_TOKEN_EXPIRES_MINUTES JWT_ACCESS_TOKEN_EXPIRES_MINUTES
export JWT_ACCESS_TOKEN_EXPIRES_MINUTES="${JWT_ACCESS_TOKEN_EXPIRES_MINUTES:-60}"

# S3 — map AWS_S3_* GitHub vars to code names
_export_alias S3_UPLOAD_BUCKET S3_UPLOAD_BUCKET AWS_S3_VIDEO_BUCKET AWS_S3_BUCKET S3_BUCKET_NAME
_export_alias S3_AUDIO_BUCKET S3_AUDIO_BUCKET AWS_S3_AUDIO_BUCKET
_export_alias S3_BUCKET_NAME S3_BUCKET_NAME AWS_S3_BUCKET S3_UPLOAD_BUCKET

# RabbitMQ queues
_export_alias VIDEO_UPLOAD_QUEUE VIDEO_UPLOAD_QUEUE RABBITMQ_QUEUE
export VIDEO_UPLOAD_QUEUE="${VIDEO_UPLOAD_QUEUE:-video-upload-queue}"
_export_alias NOTIFICATION_QUEUE NOTIFICATION_QUEUE RABBITMQ_NOTIFICATION_QUEUE
export NOTIFICATION_QUEUE="${NOTIFICATION_QUEUE:-notification-queue}"
_export_alias GATEWAY_EVENTS_QUEUE GATEWAY_EVENTS_QUEUE
export GATEWAY_EVENTS_QUEUE="${GATEWAY_EVENTS_QUEUE:-gateway-events-queue}"
_export_alias VIDEO_UPLOAD_RETRY_QUEUE VIDEO_UPLOAD_RETRY_QUEUE
export VIDEO_UPLOAD_RETRY_QUEUE="${VIDEO_UPLOAD_RETRY_QUEUE:-video-upload-retry-queue}"
_export_alias VIDEO_UPLOAD_DLQ VIDEO_UPLOAD_DLQ
export VIDEO_UPLOAD_DLQ="${VIDEO_UPLOAD_DLQ:-video-upload-dlq}"
_export_alias VIDEO_COMPLETED_QUEUE VIDEO_COMPLETED_QUEUE
export VIDEO_COMPLETED_QUEUE="${VIDEO_COMPLETED_QUEUE:-video-completed-queue}"
_export_alias VIDEO_COMPLETED_RETRY_QUEUE VIDEO_COMPLETED_RETRY_QUEUE
export VIDEO_COMPLETED_RETRY_QUEUE="${VIDEO_COMPLETED_RETRY_QUEUE:-video-completed-retry-queue}"
_export_alias VIDEO_FAILED_QUEUE VIDEO_FAILED_QUEUE
export VIDEO_FAILED_QUEUE="${VIDEO_FAILED_QUEUE:-video-failed-queue}"

# Service hosts/ports — align GH naming with docker-compose
_export_alias AUTH_SERVICE_HOST AUTH_SERVICE_HOST AUTH_HOST GATEWAY_SERVICE_HOST
export AUTH_SERVICE_HOST="${AUTH_SERVICE_HOST:-auth-service}"
_export_alias AUTH_SERVICE_PORT AUTH_SERVICE_PORT AUTH_PORT AUTH_SERVICE_PORT
export AUTH_SERVICE_PORT="${AUTH_SERVICE_PORT:-8000}"
export AUTH_K8S_SERVICE_PORT="${AUTH_K8S_SERVICE_PORT:-80}"
export CONVERTER_K8S_SERVICE_PORT="${CONVERTER_K8S_SERVICE_PORT:-80}"
_export_alias CONVERTER_SERVICE_HOST CONVERTER_SERVICE_HOST CONVERTER_HOST
export CONVERTER_SERVICE_HOST="${CONVERTER_SERVICE_HOST:-converter-service}"
_export_alias CONVERTER_SERVICE_PORT CONVERTER_SERVICE_PORT CONVERTER_PORT CONVERTER_SERVICE_PORT
export CONVERTER_SERVICE_PORT="${CONVERTER_SERVICE_PORT:-8002}"
_export_alias GATEWAY_PORT GATEWAY_PORT GATEWAY_SERVICE_PORT
export GATEWAY_PORT="${GATEWAY_PORT:-8080}"

# Terraform defaults (safe fallbacks when GH vars not set)
export VPC_CIDR="${VPC_CIDR:-10.0.0.0/16}"
export PUBLIC_SUBNET_CIDRS="${PUBLIC_SUBNET_CIDRS:-[\"10.0.1.0/24\",\"10.0.2.0/24\"]}"
export AVAILABILITY_ZONES="${AVAILABILITY_ZONES:-[\"eu-central-1a\",\"eu-central-1b\"]}"
export ECR_REPOSITORIES="${ECR_REPOSITORIES:-[\"gateway-service\",\"auth-service\",\"converter-service\",\"notification-service\",\"frontend\"]}"
export JENKINS_INSTANCE_TYPE="${JENKINS_INSTANCE_TYPE:-t3.medium}"
export JENKINS_ASG_NAME="${JENKINS_ASG_NAME:-${PROJECT_NAME:-video-processing}-jenkins-asg}"

# EKS node group scaling defaults (used by start/stop EKS scripts)
export EKS_NODE_GROUP_NAME="${EKS_NODE_GROUP_NAME:-default}"
export EKS_DESIRED_SIZE="${EKS_DESIRED_SIZE:-2}"
export EKS_MIN_SIZE="${EKS_MIN_SIZE:-1}"
export EKS_MAX_SIZE="${EKS_MAX_SIZE:-2}"
export STRESS_TEST_REQUEST_COUNT="${STRESS_TEST_REQUEST_COUNT:-10}"
export RABBITMQ_TEST_MESSAGE_COUNT="${RABBITMQ_TEST_MESSAGE_COUNT:-5}"
export CLUSTER_AUTOSCALER_HELM_REPOSITORY="${CLUSTER_AUTOSCALER_HELM_REPOSITORY:-https://kubernetes.github.io/autoscaler}"
export CLUSTER_AUTOSCALER_HELM_CHART="${CLUSTER_AUTOSCALER_HELM_CHART:-cluster-autoscaler}"
export CLUSTER_AUTOSCALER_RELEASE_NAME="${CLUSTER_AUTOSCALER_RELEASE_NAME:-cluster-autoscaler}"
export K8S_NAMESPACE="${K8S_NAMESPACE:-${APP_NAMESPACE:-${APPLICATION_NAMESPACE:-video-processing}}}"
export MONGODB_RELEASE_NAME="${MONGODB_RELEASE_NAME:-mongodb}"
export POSTGRESQL_RELEASE_NAME="${POSTGRESQL_RELEASE_NAME:-postgresql}"
export RABBITMQ_RELEASE_NAME="${RABBITMQ_RELEASE_NAME:-rabbitmq}"
export MESSAGING_NAMESPACE="${MESSAGING_NAMESPACE:-messaging}"
export CLUSTER_AUTOSCALER_ENABLED="${CLUSTER_AUTOSCALER_ENABLED:-true}"
export KUBE_SYSTEM_NAMESPACE="${KUBE_SYSTEM_NAMESPACE:-kube-system}"
export DATABASE_NAMESPACE="${DATABASE_NAMESPACE:-database}"
export APP_NAMESPACE="${APP_NAMESPACE:-${K8S_NAMESPACE}}"
export APPLICATION_NAMESPACE="${APPLICATION_NAMESPACE:-${K8S_NAMESPACE}}"
export MONITORING_NAMESPACE="${MONITORING_NAMESPACE:-monitoring}"
export INGRESS_NAMESPACE="${INGRESS_NAMESPACE:-ingress-nginx}"
export JENKINS_NAMESPACE="${JENKINS_NAMESPACE:-jenkins}"
export STORAGE_CLASS="${STORAGE_CLASS:-ebs-gp3}"
export APP_ENV="${APP_ENV:-production}"
export PROJECT_NAME="${PROJECT_NAME:-video-processing}"
export AWS_ACCOUNT_ID="${AWS_ACCOUNT_ID:-}"
export LOG_LEVEL="${LOG_LEVEL:-info}"

# Database credentials (must precede URI construction)
export POSTGRES_PORT="${POSTGRES_PORT:-5432}"
export POSTGRES_USER="${POSTGRES_USER:-postgres}"
export POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-postgres}"
export POSTGRES_DB="${POSTGRES_DB:-video_to_audio_converter}"
export POSTGRES_SSL_MODE="${POSTGRES_SSL_MODE:-disable}"
export RABBITMQ_USERNAME="${RABBITMQ_USERNAME:-${RABBITMQ_DEFAULT_USER:-guest}}"
export RABBITMQ_PASSWORD="${RABBITMQ_PASSWORD:-${RABBITMQ_DEFAULT_PASS:-guest}}"
export RABBITMQ_DEFAULT_USER="${RABBITMQ_DEFAULT_USER:-guest}"
export RABBITMQ_DEFAULT_PASS="${RABBITMQ_DEFAULT_PASS:-guest}"
export MONGO_USERNAME="${MONGO_USERNAME:-mongo}"
export MONGO_PASSWORD="${MONGO_PASSWORD:-mongo}"
export MONGO_DATABASE="${MONGO_DATABASE:-video_converter}"
export MONGO_PORT="${MONGO_PORT:-27017}"

export DOCKER_REGISTRY_SECRET_NAME="${DOCKER_REGISTRY_SECRET_NAME:-docker-registry-secret}"
export DOCKER_IMAGE_REGISTRY="${DOCKER_IMAGE_REGISTRY:-${DOCKER_REGISTRY:-docker.io}}"
export DOCKER_IMAGE_NAMESPACE="${DOCKER_IMAGE_NAMESPACE:-${DOCKER_USERNAME:-}}"
export IMAGE_TAG="${IMAGE_TAG:-${DOCKER_IMAGE_TAG:-latest}}"

# In-cluster service discovery
export POSTGRES_HOST="${POSTGRES_HOST:-postgresql.${DATABASE_NAMESPACE}.svc.cluster.local}"
export MONGO_HOST="${MONGO_HOST:-mongodb.${DATABASE_NAMESPACE}.svc.cluster.local}"
export RABBITMQ_HOST="${RABBITMQ_HOST:-rabbitmq.${MESSAGING_NAMESPACE}.svc.cluster.local}"
export RABBITMQ_PORT="${RABBITMQ_PORT:-5672}"
export RABBITMQ_VHOST="${RABBITMQ_VHOST:-/}"
export RABBITMQ_ERLANG_COOKIE="${RABBITMQ_ERLANG_COOKIE:-production-erlang-cookie}"
export RABBITMQ_AMQP_URL="${RABBITMQ_AMQP_URL:-amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/}"
export RABBITMQ_URI="${RABBITMQ_URI:-${RABBITMQ_AMQP_URL}}"
# Built after MONGO_AUTH_SOURCE is defined (see end of file).

# Inter-service URLs
export JWT_AUTH_SERVICE_URL="${JWT_AUTH_SERVICE_URL:-http://auth-service.${K8S_NAMESPACE}.svc.cluster.local:${AUTH_K8S_SERVICE_PORT}}"
export CONVERTER_SERVICE_URL="${CONVERTER_SERVICE_URL:-http://converter-service.${K8S_NAMESPACE}.svc.cluster.local:${CONVERTER_K8S_SERVICE_PORT}}"
export NOTIFICATION_SERVICE_URL="${NOTIFICATION_SERVICE_URL:-http://notification-service.${K8S_NAMESPACE}.svc.cluster.local:80}"

# Container images
export AUTH_IMAGE="${AUTH_IMAGE:-${DOCKER_IMAGE_REGISTRY}/${DOCKER_IMAGE_NAMESPACE}/auth-service:${IMAGE_TAG}}"

# Gateway / ingress
export GATEWAY_APP_NAME="${GATEWAY_APP_NAME:-gateway-service}"
export GATEWAY_POD_LABEL="${GATEWAY_POD_LABEL:-gateway}"
export GATEWAY_WORKER_POD_LABEL="${GATEWAY_WORKER_POD_LABEL:-gateway-worker}"
export GATEWAY_REPLICA_COUNT="${GATEWAY_REPLICA_COUNT:-2}"
export GATEWAY_SERVICE_NAME="${GATEWAY_SERVICE_NAME:-gateway-service}"
export GATEWAY_SERVICE_PORT="${GATEWAY_SERVICE_PORT:-80}"
export GATEWAY_INGRESS_NAME="${GATEWAY_INGRESS_NAME:-gateway-ingress}"
export INGRESS_CLASS_NAME="${INGRESS_CLASS_NAME:-alb}"
export ALB_SCHEME="${ALB_SCHEME:-internet-facing}"
export ALB_TARGET_TYPE="${ALB_TARGET_TYPE:-ip}"
if [ -z "${ALB_LISTEN_PORTS:-}" ]; then
  if [ -n "${ACM_CERTIFICATE_ARN:-}" ] && [[ "${ACM_CERTIFICATE_ARN}" != *"placeholder"* ]]; then
    export ALB_LISTEN_PORTS='[{"HTTP":80},{"HTTPS":443}]'
  else
    export ALB_LISTEN_PORTS='[{"HTTP":80}]'
  fi
fi
export ALB_SSL_REDIRECT_PORT="${ALB_SSL_REDIRECT_PORT:-443}"
export ACM_CERTIFICATE_ARN="${ACM_CERTIFICATE_ARN:-}"
export DOMAIN_NAME="${DOMAIN_NAME:-${APP_DOMAIN:-api.example.com}}"

# Auth service deployment
export AUTH_REPLICAS="${AUTH_REPLICAS:-2}"
export AUTH_APP_NAME="${AUTH_APP_NAME:-auth-service}"
export AUTH_SERVICE_ACCOUNT="${AUTH_SERVICE_ACCOUNT:-auth-service-account}"
export AUTH_PORT="${AUTH_PORT:-8000}"
export AUTH_APP_PORT="${AUTH_APP_PORT:-8000}"
export AUTH_HEALTHCHECK_PATH="${AUTH_HEALTHCHECK_PATH:-/health}"
export AUTH_CPU_REQUEST="${AUTH_CPU_REQUEST:-100m}"
export AUTH_CPU_LIMIT="${AUTH_CPU_LIMIT:-500m}"
export AUTH_MEMORY_REQUEST="${AUTH_MEMORY_REQUEST:-256Mi}"
export AUTH_MEMORY_LIMIT="${AUTH_MEMORY_LIMIT:-512Mi}"

# Converter deployment
export CONVERTER_API_REPLICA_COUNT="${CONVERTER_API_REPLICA_COUNT:-1}"
export CONVERTER_HPA_MIN_REPLICAS="${CONVERTER_HPA_MIN_REPLICAS:-${CONVERTER_API_REPLICA_COUNT:-1}}"
export CONVERTER_MIN_REPLICA_COUNT="${CONVERTER_MIN_REPLICA_COUNT:-1}"
export CONVERTER_CPU_REQUEST="${CONVERTER_CPU_REQUEST:-250m}"
export CONVERTER_CPU_LIMIT="${CONVERTER_CPU_LIMIT:-1000m}"
export CONVERTER_MEMORY_REQUEST="${CONVERTER_MEMORY_REQUEST:-512Mi}"
export CONVERTER_MEMORY_LIMIT="${CONVERTER_MEMORY_LIMIT:-1Gi}"
export APP_PORT="${APP_PORT:-8002}"

# Notification deployment
export NOTIFICATION_REPLICAS="${NOTIFICATION_REPLICAS:-1}"
export NOTIFICATION_HPA_MIN_REPLICAS="${NOTIFICATION_HPA_MIN_REPLICAS:-${NOTIFICATION_REPLICAS:-1}}"
export NOTIFICATION_DLQ="${NOTIFICATION_DLQ:-notification-dlq}"
export MAX_NOTIFICATION_RETRIES="${MAX_NOTIFICATION_RETRIES:-3}"
export OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT:-}"
export TRACING_NAMESPACE="${TRACING_NAMESPACE:-tracing}"
export DEPLOY_TRACING_STACK="${DEPLOY_TRACING_STACK:-false}"
export DEPLOY_MTLS_STACK="${DEPLOY_MTLS_STACK:-false}"
export SYNC_RABBITMQ_DEFINITIONS="${SYNC_RABBITMQ_DEFINITIONS:-true}"
export STRICT_COOKIE_AUTH="${STRICT_COOKIE_AUTH:-false}"
export INTERNAL_TLS_CA_PATH="${INTERNAL_TLS_CA_PATH:-}"
export UPLOAD_OUTBOX_RELAY_INTERVAL_SECONDS="${UPLOAD_OUTBOX_RELAY_INTERVAL_SECONDS:-30}"
export REDIS_PVC_NAME="${REDIS_PVC_NAME:-redis-data}"
export REDIS_STORAGE_SIZE="${REDIS_STORAGE_SIZE:-1Gi}"
export NOTIFICATION_SERVICE_PORT="${NOTIFICATION_SERVICE_PORT:-8003}"
export NOTIFICATION_CPU_REQUEST="${NOTIFICATION_CPU_REQUEST:-100m}"
export NOTIFICATION_CPU_LIMIT="${NOTIFICATION_CPU_LIMIT:-500m}"
export NOTIFICATION_MEMORY_REQUEST="${NOTIFICATION_MEMORY_REQUEST:-256Mi}"
export NOTIFICATION_MEMORY_LIMIT="${NOTIFICATION_MEMORY_LIMIT:-512Mi}"
export SMTP_HOST="${SMTP_HOST:-smtp.gmail.com}"
export SMTP_PORT="${SMTP_PORT:-587}"
export SMTP_SECURE="${SMTP_SECURE:-false}"
export WEBSOCKET_HOST="${WEBSOCKET_HOST:-0.0.0.0}"
export WEBSOCKET_PORT="${WEBSOCKET_PORT:-8081}"
export GATEWAY_WORKER_REPLICAS="${GATEWAY_WORKER_REPLICAS:-2}"
export TRUST_PROXY_HEADERS="${TRUST_PROXY_HEADERS:-true}"
export INSTALL_KEDA="${INSTALL_KEDA:-true}"
export KEDA_INSTALL_TIMEOUT="${KEDA_INSTALL_TIMEOUT:-120s}"
export KEDA_SCALEDOBJECT_WAIT_TIMEOUT="${KEDA_SCALEDOBJECT_WAIT_TIMEOUT:-120s}"
export DEPLOY_JOB_WAIT_TIMEOUT="${DEPLOY_JOB_WAIT_TIMEOUT:-120s}"
export DEPLOY_ROLLOUT_TIMEOUT="${DEPLOY_ROLLOUT_TIMEOUT:-120s}"
export WORKER_ROLLOUT_TIMEOUT="${WORKER_ROLLOUT_TIMEOUT:-120s}"
export NOTIFICATION_APP_NAME="${NOTIFICATION_APP_NAME:-notification-service}"
export NOTIFICATION_POD_LABEL="${NOTIFICATION_POD_LABEL:-notification}"
export NOTIFICATION_WORKER_POD_LABEL="${NOTIFICATION_WORKER_POD_LABEL:-notification-worker}"
export NOTIFICATION_APP_PORT="${NOTIFICATION_APP_PORT:-8003}"
export EMAIL_QUEUE="${EMAIL_QUEUE:-email-queue}"
export RABBITMQ_EXCHANGE="${RABBITMQ_EXCHANGE:-video.events}"
export RABBITMQ_ROUTING_KEY="${RABBITMQ_ROUTING_KEY:-notification}"
export FRONTEND_URL="${FRONTEND_URL:-http://localhost:3000}"
_frontend_domain_from_url() {
  local url="${1#https://}"
  url="${url#http://}"
  printf '%s' "${url%%/*}"
}
export FRONTEND_DOMAIN_NAME="${FRONTEND_DOMAIN_NAME:-$(_frontend_domain_from_url "${FRONTEND_URL}")}"
export FRONTEND_INGRESS_NAME="${FRONTEND_INGRESS_NAME:-frontend-ingress}"
export FRONTEND_REPLICA_COUNT="${FRONTEND_REPLICA_COUNT:-2}"
export FRONTEND_CPU_REQUEST="${FRONTEND_CPU_REQUEST:-50m}"
export FRONTEND_CPU_LIMIT="${FRONTEND_CPU_LIMIT:-200m}"
export FRONTEND_MEMORY_REQUEST="${FRONTEND_MEMORY_REQUEST:-64Mi}"
export FRONTEND_MEMORY_LIMIT="${FRONTEND_MEMORY_LIMIT:-128Mi}"
export FRONTEND_ACM_CERTIFICATE_ARN="${FRONTEND_ACM_CERTIFICATE_ARN:-}"
export FRONTEND_IMAGE="${FRONTEND_IMAGE:-${DOCKER_IMAGE_REGISTRY}/${DOCKER_IMAGE_NAMESPACE}/frontend:${IMAGE_TAG}}"
export ALB_INGRESS_GROUP_NAME="${ALB_INGRESS_GROUP_NAME:-video-processing-public}"
export ROUTE53_HOSTED_ZONE_ID="${ROUTE53_HOSTED_ZONE_ID:-}"
export API_BASE_URL="${API_BASE_URL:-}"
export REDIS_HOST="${REDIS_HOST:-redis.${K8S_NAMESPACE}.svc.cluster.local}"
export REDIS_PORT="${REDIS_PORT:-6379}"
export REDIS_PASSWORD="${REDIS_PASSWORD:-redis}"
export EMAIL_ENABLED="${EMAIL_ENABLED:-true}"
export WEBSOCKET_NOTIFICATIONS_ENABLED="${WEBSOCKET_NOTIFICATIONS_ENABLED:-true}"
export HEALTHCHECK_PATH="${HEALTHCHECK_PATH:-/health}"
export APP_NAME="${APP_NAME:-notification-service}"
export CORS_ALLOWED_ORIGINS="${CORS_ALLOWED_ORIGINS:-*}"
if [ "${APP_ENV:-development}" = "production" ] && [ "${CORS_ALLOWED_ORIGINS}" = "*" ]; then
  if [ -n "${FRONTEND_URL:-}" ] && [ "${FRONTEND_URL}" != "http://localhost:3000" ]; then
    export CORS_ALLOWED_ORIGINS="${FRONTEND_URL}"
  elif [ -n "${FRONTEND_DOMAIN_NAME:-}" ] && [ "${FRONTEND_DOMAIN_NAME}" != "localhost" ]; then
    export CORS_ALLOWED_ORIGINS="https://${FRONTEND_DOMAIN_NAME}"
  elif [ -n "${DOMAIN_NAME:-}" ] && [ "${DOMAIN_NAME}" != "api.example.com" ]; then
    export CORS_ALLOWED_ORIGINS="https://${DOMAIN_NAME}"
  elif [ -n "${API_BASE_URL:-}" ]; then
    export CORS_ALLOWED_ORIGINS="${API_BASE_URL}"
  fi
fi
export API_PREFIX="${API_PREFIX:-/api/v1}"
export REFRESH_TOKEN_EXPIRE_DAYS="${REFRESH_TOKEN_EXPIRE_DAYS:-7}"
export MAX_VIDEO_UPLOAD_SIZE_MB="${MAX_VIDEO_UPLOAD_SIZE_MB:-500}"
export NOTIFICATION_SERVICE_HOST="${NOTIFICATION_SERVICE_HOST:-notification-service}"
export NOTIFICATION_SERVICE_PORT="${NOTIFICATION_SERVICE_PORT:-8003}"
export AWS_S3_BUCKET="${AWS_S3_BUCKET:-${S3_UPLOAD_BUCKET:-}}"
export AWS_S3_VIDEO_BUCKET="${AWS_S3_VIDEO_BUCKET:-${S3_UPLOAD_BUCKET:-}}"
export AWS_S3_AUDIO_BUCKET="${AWS_S3_AUDIO_BUCKET:-${S3_AUDIO_BUCKET:-}}"
export S3_THUMBNAIL_BUCKET="${S3_THUMBNAIL_BUCKET:-}"

# JWT extras
export JWT_REFRESH_TOKEN_EXPIRES_DAYS="${JWT_REFRESH_TOKEN_EXPIRES_DAYS:-7}"
export JWT_EXPIRATION_MINUTES="${JWT_EXPIRATION_MINUTES:-60}"
export JWT_ISSUER="${JWT_ISSUER:-video-converter-platform}"
export JWT_AUDIENCE="${JWT_AUDIENCE:-video-converter-users}"

# Auth service configmap defaults
export ACCESS_TOKEN_EXPIRE_MINUTES="${ACCESS_TOKEN_EXPIRE_MINUTES:-${JWT_ACCESS_TOKEN_EXPIRES_MINUTES:-60}}"
export PASSWORD_HASH_SCHEME="${PASSWORD_HASH_SCHEME:-bcrypt}"
export AUTH_EVENTS_QUEUE="${AUTH_EVENTS_QUEUE:-auth-events-queue}"
export AUTH_RETRY_QUEUE="${AUTH_RETRY_QUEUE:-auth-retry-queue}"
export DATABASE_POOL_SIZE="${DATABASE_POOL_SIZE:-${POSTGRES_POOL_SIZE:-10}}"
export DATABASE_MAX_OVERFLOW="${DATABASE_MAX_OVERFLOW:-${POSTGRES_MAX_OVERFLOW:-20}}"
export DATABASE_POOL_TIMEOUT="${DATABASE_POOL_TIMEOUT:-${POSTGRES_POOL_TIMEOUT:-30}}"
export SECURE_COOKIES="${SECURE_COOKIES:-false}"
export COOKIE_SAMESITE="${COOKIE_SAMESITE:-lax}"
export COOKIE_SECURE="${COOKIE_SECURE:-false}"

# Converter service configmap defaults
export CONVERTER_APP_NAME="${CONVERTER_APP_NAME:-converter-service}"
export CONVERTER_WORKER_POD_LABEL="${CONVERTER_WORKER_POD_LABEL:-converter-worker}"
export CONVERTER_APP_PORT="${CONVERTER_APP_PORT:-8002}"
export CONVERTER_HEALTHCHECK_PATH="${CONVERTER_HEALTHCHECK_PATH:-/health}"
export S3_VIDEO_UPLOAD_PREFIX="${S3_VIDEO_UPLOAD_PREFIX:-uploads/videos/}"
export S3_AUDIO_OUTPUT_PREFIX="${S3_AUDIO_OUTPUT_PREFIX:-outputs/audio/}"
export S3_VIDEO_UPLOAD_EXPIRATION_DAYS="${S3_VIDEO_UPLOAD_EXPIRATION_DAYS:-7}"
export S3_AUDIO_OUTPUT_EXPIRATION_DAYS="${S3_AUDIO_OUTPUT_EXPIRATION_DAYS:-7}"
export FFMPEG_THREADS="${FFMPEG_THREADS:-2}"
export MAX_VIDEO_SIZE_MB="${MAX_VIDEO_SIZE_MB:-${MAX_VIDEO_UPLOAD_SIZE_MB:-500}}"
export ALLOWED_VIDEO_EXTENSIONS="${ALLOWED_VIDEO_EXTENSIONS:-mp4,mov,avi,mkv,webm}"
export OUTPUT_AUDIO_FORMAT="${OUTPUT_AUDIO_FORMAT:-mp3}"
export TEMP_STORAGE_PATH="${TEMP_STORAGE_PATH:-/tmp/converter}"
export OUTPUT_STORAGE_PATH="${OUTPUT_STORAGE_PATH:-/tmp/converter/output}"
export CONVERSION_WORKER_CONCURRENCY="${CONVERSION_WORKER_CONCURRENCY:-2}"
export MAX_CONVERSION_TIMEOUT_SECONDS="${MAX_CONVERSION_TIMEOUT_SECONDS:-90}"

# Postgres pool defaults (optional secret fields)
export POSTGRES_POOL_SIZE="${POSTGRES_POOL_SIZE:-10}"
export POSTGRES_MAX_OVERFLOW="${POSTGRES_MAX_OVERFLOW:-20}"
export POSTGRES_POOL_TIMEOUT="${POSTGRES_POOL_TIMEOUT:-30}"
export POSTGRES_POOL_RECYCLE="${POSTGRES_POOL_RECYCLE:-1800}"
export POSTGRES_CONNECT_TIMEOUT="${POSTGRES_CONNECT_TIMEOUT:-10}"
export POSTGRES_READ_HOST="${POSTGRES_READ_HOST:-}"
export POSTGRES_READ_PORT="${POSTGRES_READ_PORT:-5432}"
export POSTGRES_BACKUP_BUCKET="${POSTGRES_BACKUP_BUCKET:-}"
export POSTGRES_BACKUP_PREFIX="${POSTGRES_BACKUP_PREFIX:-}"

# MongoDB Helm defaults
export MONGODB_REPLICA_COUNT="${MONGODB_REPLICA_COUNT:-1}"
export MONGODB_IMAGE_REPOSITORY="${MONGODB_IMAGE_REPOSITORY:-mongo}"
export MONGODB_IMAGE_TAG="${MONGODB_IMAGE_TAG:-7.0}"
export MONGODB_IMAGE_PULL_POLICY="${MONGODB_IMAGE_PULL_POLICY:-IfNotPresent}"
export MONGODB_SERVICE_TYPE="${MONGODB_SERVICE_TYPE:-ClusterIP}"
export MONGODB_PORT="${MONGODB_PORT:-27017}"
export MONGODB_STORAGE_SIZE="${MONGODB_STORAGE_SIZE:-10Gi}"
export MONGODB_ARCHITECTURE="${MONGODB_ARCHITECTURE:-standalone}"
export MONGODB_CPU_REQUEST="${MONGODB_CPU_REQUEST:-250m}"
export MONGODB_MEMORY_REQUEST="${MONGODB_MEMORY_REQUEST:-512Mi}"
export MONGODB_CPU_LIMIT="${MONGODB_CPU_LIMIT:-1000m}"
export MONGODB_MEMORY_LIMIT="${MONGODB_MEMORY_LIMIT:-1Gi}"
export MONGODB_AUTOSCALING_ENABLED="${MONGODB_AUTOSCALING_ENABLED:-false}"
export MONGODB_AUTOSCALING_MIN_REPLICAS="${MONGODB_AUTOSCALING_MIN_REPLICAS:-1}"
export MONGODB_AUTOSCALING_MAX_REPLICAS="${MONGODB_AUTOSCALING_MAX_REPLICAS:-3}"
export MONGODB_AUTOSCALING_TARGET_CPU="${MONGODB_AUTOSCALING_TARGET_CPU:-80}"
export MONGODB_METRICS_ENABLED="${MONGODB_METRICS_ENABLED:-false}"
export MONGODB_SERVICE_MONITOR_ENABLED="${MONGODB_SERVICE_MONITOR_ENABLED:-false}"
export MONGODB_BACKUP_ENABLED="${MONGODB_BACKUP_ENABLED:-false}"
export MONGODB_BACKUP_SCHEDULE="${MONGODB_BACKUP_SCHEDULE:-0 2 * * *}"
export MONGODB_BACKUP_RETENTION="${MONGODB_BACKUP_RETENTION:-7}"
export MONGODB_ARBITER_ENABLED="${MONGODB_ARBITER_ENABLED:-false}"
export MONGODB_REPLICA_SET_NAME="${MONGODB_REPLICA_SET_NAME:-rs0}"
export MONGODB_CACHE_SIZE_GB="${MONGODB_CACHE_SIZE_GB:-1}"
export MONGODB_MAX_CONNECTIONS="${MONGODB_MAX_CONNECTIONS:-1000}"
export MONGO_AUTH_SOURCE="${MONGO_AUTH_SOURCE:-admin}"

_mongo_password_urlencoded() {
  python3 -c "import urllib.parse, os; print(urllib.parse.quote_plus(os.environ['MONGO_PASSWORD']))"
}

if [ -z "${MONGO_URI:-}" ]; then
  export MONGO_URI="mongodb://${MONGO_USERNAME}:$(_mongo_password_urlencoded)@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DATABASE}?authSource=${MONGO_AUTH_SOURCE}"
fi

# PostgreSQL Helm defaults
export POSTGRES_REPLICA_COUNT="${POSTGRES_REPLICA_COUNT:-1}"
export POSTGRES_IMAGE_REPOSITORY="${POSTGRES_IMAGE_REPOSITORY:-postgres}"
export POSTGRES_IMAGE_TAG="${POSTGRES_IMAGE_TAG:-16-alpine}"
export POSTGRES_IMAGE_PULL_POLICY="${POSTGRES_IMAGE_PULL_POLICY:-IfNotPresent}"
export POSTGRES_SERVICE_TYPE="${POSTGRES_SERVICE_TYPE:-ClusterIP}"
export POSTGRES_STORAGE_SIZE="${POSTGRES_STORAGE_SIZE:-10Gi}"
export POSTGRES_ARCHITECTURE="${POSTGRES_ARCHITECTURE:-standalone}"
export POSTGRES_REPLICATION_ENABLED="${POSTGRES_REPLICATION_ENABLED:-false}"
export POSTGRES_CPU_REQUEST="${POSTGRES_CPU_REQUEST:-250m}"
export POSTGRES_MEMORY_REQUEST="${POSTGRES_MEMORY_REQUEST:-512Mi}"
export POSTGRES_CPU_LIMIT="${POSTGRES_CPU_LIMIT:-1000m}"
export POSTGRES_MEMORY_LIMIT="${POSTGRES_MEMORY_LIMIT:-1Gi}"
export POSTGRES_AUTOSCALING_ENABLED="${POSTGRES_AUTOSCALING_ENABLED:-false}"
export POSTGRES_AUTOSCALING_MIN_REPLICAS="${POSTGRES_AUTOSCALING_MIN_REPLICAS:-1}"
export POSTGRES_AUTOSCALING_MAX_REPLICAS="${POSTGRES_AUTOSCALING_MAX_REPLICAS:-3}"
export POSTGRES_AUTOSCALING_TARGET_CPU="${POSTGRES_AUTOSCALING_TARGET_CPU:-80}"
export POSTGRES_METRICS_ENABLED="${POSTGRES_METRICS_ENABLED:-false}"
export POSTGRES_SERVICE_MONITOR_ENABLED="${POSTGRES_SERVICE_MONITOR_ENABLED:-false}"
export POSTGRES_BACKUP_ENABLED="${POSTGRES_BACKUP_ENABLED:-false}"
export POSTGRES_BACKUP_SCHEDULE="${POSTGRES_BACKUP_SCHEDULE:-0 3 * * *}"
export POSTGRES_BACKUP_RETENTION="${POSTGRES_BACKUP_RETENTION:-7}"
export POSTGRES_MAX_CONNECTIONS="${POSTGRES_MAX_CONNECTIONS:-200}"
export POSTGRES_SHARED_BUFFERS="${POSTGRES_SHARED_BUFFERS:-256MB}"
export POSTGRES_EFFECTIVE_CACHE_SIZE="${POSTGRES_EFFECTIVE_CACHE_SIZE:-768MB}"
export POSTGRES_MAINTENANCE_WORK_MEM="${POSTGRES_MAINTENANCE_WORK_MEM:-64MB}"

# RabbitMQ Helm defaults
export RABBITMQ_REPLICA_COUNT="${RABBITMQ_REPLICA_COUNT:-1}"
export RABBITMQ_IMAGE_REPOSITORY="${RABBITMQ_IMAGE_REPOSITORY:-rabbitmq}"
export RABBITMQ_IMAGE_TAG="${RABBITMQ_IMAGE_TAG:-3.13-management-alpine}"
export RABBITMQ_IMAGE_PULL_POLICY="${RABBITMQ_IMAGE_PULL_POLICY:-IfNotPresent}"
export RABBITMQ_SERVICE_TYPE="${RABBITMQ_SERVICE_TYPE:-ClusterIP}"
export RABBITMQ_AMQP_PORT="${RABBITMQ_AMQP_PORT:-5672}"
export RABBITMQ_MANAGEMENT_PORT="${RABBITMQ_MANAGEMENT_PORT:-15672}"
export RABBITMQ_PERSISTENCE_ENABLED="${RABBITMQ_PERSISTENCE_ENABLED:-true}"
export RABBITMQ_STORAGE_SIZE="${RABBITMQ_STORAGE_SIZE:-5Gi}"
export RABBITMQ_REQUEST_CPU="${RABBITMQ_REQUEST_CPU:-250m}"
export RABBITMQ_REQUEST_MEMORY="${RABBITMQ_REQUEST_MEMORY:-512Mi}"
export RABBITMQ_LIMIT_CPU="${RABBITMQ_LIMIT_CPU:-1000m}"
export RABBITMQ_LIMIT_MEMORY="${RABBITMQ_LIMIT_MEMORY:-1Gi}"
export RABBITMQ_RUN_AS_USER="${RABBITMQ_RUN_AS_USER:-999}"
export RABBITMQ_LIVENESS_INITIAL_DELAY_SECONDS="${RABBITMQ_LIVENESS_INITIAL_DELAY_SECONDS:-60}"
export RABBITMQ_LIVENESS_PERIOD_SECONDS="${RABBITMQ_LIVENESS_PERIOD_SECONDS:-30}"
export RABBITMQ_LIVENESS_TIMEOUT_SECONDS="${RABBITMQ_LIVENESS_TIMEOUT_SECONDS:-10}"
export RABBITMQ_LIVENESS_FAILURE_THRESHOLD="${RABBITMQ_LIVENESS_FAILURE_THRESHOLD:-6}"
export RABBITMQ_READINESS_INITIAL_DELAY_SECONDS="${RABBITMQ_READINESS_INITIAL_DELAY_SECONDS:-20}"
export RABBITMQ_READINESS_PERIOD_SECONDS="${RABBITMQ_READINESS_PERIOD_SECONDS:-10}"
export RABBITMQ_READINESS_TIMEOUT_SECONDS="${RABBITMQ_READINESS_TIMEOUT_SECONDS:-5}"
export RABBITMQ_READINESS_FAILURE_THRESHOLD="${RABBITMQ_READINESS_FAILURE_THRESHOLD:-6}"
export RABBITMQ_STARTUP_FAILURE_THRESHOLD="${RABBITMQ_STARTUP_FAILURE_THRESHOLD:-30}"
export RABBITMQ_STARTUP_PERIOD_SECONDS="${RABBITMQ_STARTUP_PERIOD_SECONDS:-10}"
export RABBITMQ_AUTOSCALING_ENABLED="${RABBITMQ_AUTOSCALING_ENABLED:-false}"
export RABBITMQ_AUTOSCALING_MIN_REPLICAS="${RABBITMQ_AUTOSCALING_MIN_REPLICAS:-1}"
export RABBITMQ_AUTOSCALING_MAX_REPLICAS="${RABBITMQ_AUTOSCALING_MAX_REPLICAS:-3}"
export RABBITMQ_TARGET_CPU_UTILIZATION_PERCENTAGE="${RABBITMQ_TARGET_CPU_UTILIZATION_PERCENTAGE:-80}"
export RABBITMQ_APP_LABEL="${RABBITMQ_APP_LABEL:-rabbitmq}"

# Toolchain URL defaults
export UBUNTU_AMI_OWNERS="${UBUNTU_AMI_OWNERS:-[\"099720109477\"]}"
export UBUNTU_AMI_NAME_FILTER="${UBUNTU_AMI_NAME_FILTER:-[\"ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-*\"]}"
export DOCKER_GPG_URL="${DOCKER_GPG_URL:-https://download.docker.com/linux/ubuntu/gpg}"
export DOCKER_REPO_URL="${DOCKER_REPO_URL:-https://download.docker.com/linux/ubuntu}"
export JENKINS_GPG_URL="${JENKINS_GPG_URL:-https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key}"
export JENKINS_REPO_URL="${JENKINS_REPO_URL:-https://pkg.jenkins.io/debian-stable binary/}"
export AWSCLI_ZIP_URL="${AWSCLI_ZIP_URL:-https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip}"
export KUBECTL_STABLE_URL="${KUBECTL_STABLE_URL:-https://dl.k8s.io/release/stable.txt}"
export KUBECTL_BINARY_BASE_URL="${KUBECTL_BINARY_BASE_URL:-https://dl.k8s.io/release}"
export HELM_INSTALL_SCRIPT_URL="${HELM_INSTALL_SCRIPT_URL:-https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3}"
export HASHICORP_GPG_URL="${HASHICORP_GPG_URL:-https://apt.releases.hashicorp.com/gpg}"
export HASHICORP_REPO_URL="${HASHICORP_REPO_URL:-https://apt.releases.hashicorp.com}"
export EKSCTL_DOWNLOAD_URL="${EKSCTL_DOWNLOAD_URL:-https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz}"
export JENKINS_CONTAINER_IMAGE="${JENKINS_CONTAINER_IMAGE:-jenkins/jenkins:lts}"
export JENKINS_CONTAINER_NAME="${JENKINS_CONTAINER_NAME:-jenkins}"
export JENKINS_VOLUME_NAME="${JENKINS_VOLUME_NAME:-jenkins-data}"
export JENKINS_HOST_PORT="${JENKINS_HOST_PORT:-8080}"
export JENKINS_AGENT_PORT="${JENKINS_AGENT_PORT:-50000}"
export JENKINS_ROOT_VOLUME_SIZE="${JENKINS_ROOT_VOLUME_SIZE:-50}"

# Network policy defaults (ALB ingress uses VPC CIDR; target-type ip hits pod ports)
export GATEWAY_NAMESPACE="${GATEWAY_NAMESPACE:-${K8S_NAMESPACE}}"
export GATEWAY_NETWORK_POLICY_NAME="${GATEWAY_NETWORK_POLICY_NAME:-gateway-network-policy}"
export GATEWAY_NETWORK_POLICY_LABEL="${GATEWAY_NETWORK_POLICY_LABEL:-gateway-access}"
export AUTH_NETWORK_POLICY_NAME="${AUTH_NETWORK_POLICY_NAME:-auth-network-policy}"
export AUTH_COMPONENT_NAME="${AUTH_COMPONENT_NAME:-auth}"
export AUTH_NETWORK_POLICY_LABEL="${AUTH_NETWORK_POLICY_LABEL:-auth-access}"
export CONVERTER_NETWORK_POLICY_NAME="${CONVERTER_NETWORK_POLICY_NAME:-converter-network-policy}"
export CONVERTER_COMPONENT_NAME="${CONVERTER_COMPONENT_NAME:-converter}"
export CONVERTER_NETWORK_POLICY_LABEL="${CONVERTER_NETWORK_POLICY_LABEL:-converter-access}"
export NOTIFICATION_COMPONENT_NAME="${NOTIFICATION_COMPONENT_NAME:-notification}"
export NOTIFICATION_NETWORK_POLICY_NAME="${NOTIFICATION_NETWORK_POLICY_NAME:-notification-network-policy}"
export NOTIFICATION_NETWORK_POLICY_LABEL="${NOTIFICATION_NETWORK_POLICY_LABEL:-notification-access}"
export FRONTEND_NETWORK_POLICY_NAME="${FRONTEND_NETWORK_POLICY_NAME:-frontend-network-policy}"
export FRONTEND_APP_PORT="${FRONTEND_APP_PORT:-3000}"
export REDIS_NETWORK_POLICY_NAME="${REDIS_NETWORK_POLICY_NAME:-redis-network-policy}"
export REDIS_PORT="${REDIS_PORT:-6379}"
export POSTGRES_APP_NAME="${POSTGRES_APP_NAME:-postgresql}"
export MONGODB_APP_NAME="${MONGODB_APP_NAME:-mongodb}"
export RABBITMQ_APP_NAME="${RABBITMQ_APP_NAME:-rabbitmq}"
export RABBITMQ_AMQP_PORT="${RABBITMQ_AMQP_PORT:-5672}"
export RABBITMQ_MANAGEMENT_PORT="${RABBITMQ_MANAGEMENT_PORT:-15672}"
export RABBITMQ_ERLANG_PORT="${RABBITMQ_ERLANG_PORT:-4369}"
export RABBITMQ_CLUSTERING_PORT="${RABBITMQ_CLUSTERING_PORT:-25672}"
export DNS_PORT="${DNS_PORT:-53}"
export HTTP_PORT="${HTTP_PORT:-80}"
export HTTPS_PORT="${HTTPS_PORT:-443}"
export PROMETHEUS_REPLICAS="${PROMETHEUS_REPLICAS:-1}"
export PROMETHEUS_IMAGE="${PROMETHEUS_IMAGE:-prom/prometheus:v2.54.1}"
export PROMETHEUS_CPU_REQUEST="${PROMETHEUS_CPU_REQUEST:-100m}"
export PROMETHEUS_CPU_LIMIT="${PROMETHEUS_CPU_LIMIT:-500m}"
export PROMETHEUS_MEMORY_REQUEST="${PROMETHEUS_MEMORY_REQUEST:-256Mi}"
export PROMETHEUS_MEMORY_LIMIT="${PROMETHEUS_MEMORY_LIMIT:-512Mi}"
export GRAFANA_REPLICAS="${GRAFANA_REPLICAS:-1}"
export GRAFANA_REPLICA_COUNT="${GRAFANA_REPLICA_COUNT:-1}"
export GRAFANA_IMAGE="${GRAFANA_IMAGE:-grafana/grafana:11.2.0}"
export GRAFANA_SERVICE_TYPE="${GRAFANA_SERVICE_TYPE:-ClusterIP}"
export GRAFANA_ADMIN_USER="${GRAFANA_ADMIN_USER:-admin}"
export GRAFANA_ADMIN_PASSWORD="${GRAFANA_ADMIN_PASSWORD:-changeme}"
export PROMETHEUS_LABEL_KEY="${PROMETHEUS_LABEL_KEY:-app}"
export PROMETHEUS_LABEL_VALUE="${PROMETHEUS_LABEL_VALUE:-prometheus}"
export APPLY_NETWORK_POLICIES="${APPLY_NETWORK_POLICIES:-true}"
export DEPLOY_MONITORING_STACK="${DEPLOY_MONITORING_STACK:-true}"

# KEDA autoscaling defaults
export KEDA_NAMESPACE="${KEDA_NAMESPACE:-keda}"
export CONVERTER_SCALEDOBJECT_NAME="${CONVERTER_SCALEDOBJECT_NAME:-converter-worker-scaler}"
export CONVERTER_COMPONENT_NAME="${CONVERTER_COMPONENT_NAME:-converter-worker}"
export MANAGED_BY="${MANAGED_BY:-kubectl}"
export KEDA_POLLING_INTERVAL="${KEDA_POLLING_INTERVAL:-30}"
export KEDA_COOLDOWN_PERIOD="${KEDA_COOLDOWN_PERIOD:-300}"
export CONVERTER_MIN_REPLICA_COUNT="${CONVERTER_MIN_REPLICA_COUNT:-1}"
export CONVERTER_MAX_REPLICA_COUNT="${CONVERTER_MAX_REPLICA_COUNT:-5}"
export KEDA_RESTORE_TO_ORIGINAL_REPLICA_COUNT="${KEDA_RESTORE_TO_ORIGINAL_REPLICA_COUNT:-false}"
export KEDA_SCALE_UP_STABILIZATION_WINDOW_SECONDS="${KEDA_SCALE_UP_STABILIZATION_WINDOW_SECONDS:-0}"
export KEDA_SCALE_UP_POLICY_TYPE="${KEDA_SCALE_UP_POLICY_TYPE:-Pods}"
export KEDA_SCALE_UP_POLICY_VALUE="${KEDA_SCALE_UP_POLICY_VALUE:-2}"
export KEDA_SCALE_UP_POLICY_PERIOD_SECONDS="${KEDA_SCALE_UP_POLICY_PERIOD_SECONDS:-60}"
export KEDA_SCALE_DOWN_STABILIZATION_WINDOW_SECONDS="${KEDA_SCALE_DOWN_STABILIZATION_WINDOW_SECONDS:-300}"
export KEDA_SCALE_DOWN_POLICY_TYPE="${KEDA_SCALE_DOWN_POLICY_TYPE:-Pods}"
export KEDA_SCALE_DOWN_POLICY_VALUE="${KEDA_SCALE_DOWN_POLICY_VALUE:-1}"
export KEDA_SCALE_DOWN_POLICY_PERIOD_SECONDS="${KEDA_SCALE_DOWN_POLICY_PERIOD_SECONDS:-60}"
export KEDA_TRIGGER_TYPE="${KEDA_TRIGGER_TYPE:-rabbitmq}"
export RABBITMQ_PROTOCOL="${RABBITMQ_PROTOCOL:-amqp}"
export KEDA_TRIGGER_MODE="${KEDA_TRIGGER_MODE:-QueueLength}"
export KEDA_QUEUE_LENGTH_THRESHOLD="${KEDA_QUEUE_LENGTH_THRESHOLD:-5}"
export KEDA_ACTIVATION_QUEUE_LENGTH="${KEDA_ACTIVATION_QUEUE_LENGTH:-1}"
export KEDA_TRIGGER_AUTH_NAME="${KEDA_TRIGGER_AUTH_NAME:-rabbitmq-trigger-auth}"
export RABBITMQ_HOST_ENV_VARIABLE="${RABBITMQ_HOST_ENV_VARIABLE:-RABBITMQ_URI}"

if [ "${APP_ENV:-development}" = "production" ] && [ "${POSTGRES_SSL_MODE:-disable}" = "disable" ]; then
  if [[ "${POSTGRES_HOST:-}" == *".svc.cluster.local"* ]]; then
    export POSTGRES_SSL_MODE="prefer"
  else
    export POSTGRES_SSL_MODE="require"
  fi
fi

if [ "${DEPLOY_TRACING_STACK:-false}" = "true" ] && [ -z "${OTEL_EXPORTER_OTLP_ENDPOINT:-}" ]; then
  export OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-collector.${TRACING_NAMESPACE}.svc.cluster.local:4318"
fi

if [ "${APP_ENV:-development}" = "production" ]; then
  export RATE_LIMIT_FAIL_CLOSED="${RATE_LIMIT_FAIL_CLOSED:-true}"
  export STRICT_COOKIE_AUTH="${STRICT_COOKIE_AUTH:-true}"
else
  export RATE_LIMIT_FAIL_CLOSED="${RATE_LIMIT_FAIL_CLOSED:-false}"
fi

# SMTP alias
_export_alias SMTP_EMAIL SMTP_EMAIL SMTP_USERNAME
_export_alias SMTP_USERNAME SMTP_USERNAME SMTP_EMAIL
_export_alias SMTP_FROM_EMAIL SMTP_FROM_EMAIL SMTP_EMAIL SMTP_USERNAME
