apiVersion: v1
kind: ConfigMap

metadata:
  name: auth-config
  namespace: ${K8S_NAMESPACE}

data:
  APP_NAME: "${AUTH_APP_NAME}"
  APP_ENV: "${APP_ENV}"
  APP_PORT: "${AUTH_PORT}"

  DATABASE_HOST: "${POSTGRES_HOST}"
  DATABASE_PORT: "${POSTGRES_PORT}"
  DATABASE_NAME: "${POSTGRES_DB}"