apiVersion: apps/v1

kind: Deployment

metadata:
  name: auth-deployment
  namespace: video-converter

spec:

  replicas: 2

  selector:
    matchLabels:
      app: auth

  template:

    metadata:
      labels:
        app: auth

    spec:

      containers:

        - name: auth

          image: your-dockerhub-username/auth-service:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 8001

          envFrom:

            - configMapRef:
                name: auth-config

            - secretRef:
                name: auth-secret

          resources:

            requests:
              cpu: "200m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"