apiVersion: v1

kind: Service

metadata:
  name: auth-service
  namespace: ${K8S_NAMESPACE}

spec:

  selector:
    app: auth-service

  ports:

    - name: http
      protocol: TCP
      port: 80
      targetPort: ${AUTH_APP_PORT}

    - name: https
      protocol: TCP
      port: ${INTERNAL_TLS_PORT}
      targetPort: ${INTERNAL_TLS_PORT}

  type: ClusterIP
