apiVersion: v1

kind: Service

metadata:
  name: auth-service
  namespace: ${K8S_NAMESPACE}

spec:

  selector:
    app: auth-service

  ports:

    - protocol: TCP
      port: 80
      targetPort: ${AUTH_APP_PORT}

  type: ClusterIP
