apiVersion: v1

kind: ConfigMap

metadata:
  name: converter-config
  namespace: video-converter

data:

  APP_NAME: "converter-service"

  APP_ENV: "production"

  APP_PORT: "8002"

  RABBITMQ_HOST: "rabbitmq"

  RABBITMQ_PORT: "5672"

  MONGODB_URI: "mongodb://admin:password123@mongodb:27017"

  AWS_REGION: "eu-west-2"

  S3_UPLOAD_BUCKET: "video-converter-uploads-sam"

  S3_AUDIO_BUCKET: "video-converter-audio-sam"

  S3_THUMBNAIL_BUCKET: "video-converter-thumbnails-sam"