# ==========================================================
# CONFIGMAP
# ==========================================================

apiVersion: v1
kind: ConfigMap

metadata:
  name: converter-config
  namespace: video-converter

data:
  APP_NAME: "converter-service"
  APP_ENV: "${APP_ENV}"
  APP_PORT: "${APP_PORT}"

  AWS_REGION: "${AWS_REGION}"

  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT}"
  RABBITMQ_VHOST: "${RABBITMQ_VHOST}"

  MONGO_HOST: "${MONGO_HOST}"
  MONGO_PORT: "${MONGO_PORT}"
  MONGO_DATABASE: "${MONGO_DATABASE}"

  S3_UPLOAD_BUCKET: "${S3_UPLOAD_BUCKET}"
  S3_AUDIO_BUCKET: "${S3_AUDIO_BUCKET}"
  S3_THUMBNAIL_BUCKET: "${S3_THUMBNAIL_BUCKET}"

---
# ==========================================================
# MONGODB SECRET
# ==========================================================

apiVersion: v1
