kind: Secret

metadata:
  name: mongodb-secret
  namespace: ${K8S_NAMESPACE}

type: Opaque

stringData:
  MONGO_USERNAME: "${MONGO_USERNAME}"
  MONGO_PASSWORD: "${MONGO_PASSWORD}"
  MONGO_URI: "${MONGO_URI}"

