# ==========================================================
# RABBITMQ SECRET
# ==========================================================

apiVersion: v1
kind: Secret

metadata:
  name: rabbitmq-secret
  namespace: video-converter

type: Opaque

stringData:
  RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  RABBITMQ_URI: "${RABBITMQ_URI}"

# ==========================================================
# DEPLOYMENT
# ==========================================================

apiVersion: apps/v1
