apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: ${K8S_NAMESPACE}
type: Opaque
stringData:
  RABBITMQ_USERNAME: "${RABBITMQ_USERNAME}"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  RABBITMQ_HOST: "${RABBITMQ_HOST}"
  RABBITMQ_PORT: "${RABBITMQ_PORT}"
  RABBITMQ_URI: "${RABBITMQ_URI}"
  KEDA_RABBITMQ_HOST: "${KEDA_RABBITMQ_HOST}"
