apiVersion: v1

kind: Service

metadata:
  name: converter-service
  namespace: ${K8S_NAMESPACE}

spec:

  selector:
    app: converter

  ports:

    - protocol: TCP
      port: 80
      targetPort: 8002

  type: ClusterIP
