#!/bin/bash
# Export non-secret scalar variables to GITHUB_ENV for GitHub Actions.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib/env-aliases.sh
source "${ROOT_DIR}/scripts/lib/env-aliases.sh"

if [ -z "${GITHUB_ENV:-}" ]; then
  exit 0
fi

keys=(
  AWS_REGION PROJECT_NAME APP_ENV EKS_CLUSTER_NAME EKS_NODE_GROUP_NAME
  EKS_INSTANCE_TYPE EKS_DESIRED_SIZE EKS_MIN_SIZE EKS_MAX_SIZE
  TF_STATE_BUCKET TF_LOCK_TABLE K8S_NAMESPACE MESSAGING_NAMESPACE DATABASE_NAMESPACE
  DOCKER_IMAGE_REGISTRY DOCKER_IMAGE_NAMESPACE IMAGE_TAG DOCKER_USERNAME
  VPC_CIDR PUBLIC_SUBNET_CIDRS PRIVATE_SUBNET_CIDRS AVAILABILITY_ZONES
  ECR_REPOSITORIES JENKINS_INSTANCE_TYPE CLUSTER_AUTOSCALER_ENABLED
  CLUSTER_AUTOSCALER_RELEASE_NAME CLUSTER_AUTOSCALER_HELM_REPOSITORY
  CLUSTER_AUTOSCALER_HELM_CHART KUBE_SYSTEM_NAMESPACE GATEWAY_RELEASE_NAME
  APP_DOMAIN DOMAIN_NAME API_BASE_URL FRONTEND_URL FRONTEND_DOMAIN_NAME
  JWT_AUTH_SERVICE_URL ALB_INGRESS_GROUP_NAME ROUTE53_HOSTED_ZONE_ID FRONTEND_IMAGE
  AUTH_K8S_SERVICE_PORT CONVERTER_K8S_SERVICE_PORT SMTP_SECURE
  AWS_S3_VIDEO_BUCKET AWS_S3_AUDIO_BUCKET AWS_S3_BUCKET
  S3_UPLOAD_BUCKET S3_AUDIO_BUCKET S3_BUCKET_NAME
  S3_VIDEO_UPLOAD_EXPIRATION_DAYS S3_AUDIO_OUTPUT_EXPIRATION_DAYS
  ACM_CERTIFICATE_ARN ALB_LISTEN_PORTS ALB_SSL_REDIRECT_PORT
)

for key in "${keys[@]}"; do
  value="${!key:-}"
  if [ -n "$value" ]; then
    echo "${key}=${value}" >> "$GITHUB_ENV"
  fi
done
