#!/bin/bash
# Export non-secret scalar variables to GITHUB_ENV for GitHub Actions.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
# shellcheck source=scripts/lib/env-aliases.sh
source "${ROOT_DIR}/scripts/lib/env-aliases.sh"

if [ -z "${GITHUB_ENV:-}" ]; then
  exit 0
fi

keys=(
  AWS_REGION PROJECT_NAME APP_ENV EKS_CLUSTER_NAME EKS_NODE_GROUP_NAME
  EKS_INSTANCE_TYPE EKS_DESIRED_SIZE EKS_MIN_SIZE EKS_MAX_SIZE
  TF_STATE_BUCKET TF_LOCK_TABLE K8S_NAMESPACE MESSAGING_NAMESPACE DATABASE_NAMESPACE
  DOCKER_IMAGE_REGISTRY DOCKER_IMAGE_NAMESPACE IMAGE_TAG DOCKER_USERNAME
  VPC_CIDR PUBLIC_SUBNET_CIDRS PRIVATE_SUBNET_CIDRS AVAILABILITY_ZONES
  ECR_REPOSITORIES JENKINS_INSTANCE_TYPE CLUSTER_AUTOSCALER_ENABLED
  CLUSTER_AUTOSCALER_RELEASE_NAME CLUSTER_AUTOSCALER_HELM_REPOSITORY
  CLUSTER_AUTOSCALER_HELM_CHART KUBE_SYSTEM_NAMESPACE GATEWAY_RELEASE_NAME
)

for key in "${keys[@]}"; do
  value="${!key:-}"
  if [ -n "$value" ]; then
    echo "${key}=${value}" >> "$GITHUB_ENV"
  fi
done
