#!/bin/bash
# Render Kubernetes Secret manifests via kubectl (handles multiline PEM, special chars, numeric passwords).
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUTPUT_DIR="${1:?output directory required}"
SECRETS_DIR="${OUTPUT_DIR}/infrastructure/kubernetes/secrets"

# shellcheck source=scripts/lib/env-aliases.sh
source "${ROOT_DIR}/scripts/lib/env-aliases.sh"

_strip_control_chars() {
  printf '%s' "${1}" | tr -d '\000-\010\013\014\016-\037'
}

_sanitize_secret_env() {
  local key
  for key in \
    JWT_SECRET JWT_PRIVATE_KEY JWT_PUBLIC_KEY JWT_REFRESH_TOKEN_SECRET JWT_SESSION_SECRET \
    POSTGRES_PASSWORD POSTGRES_USER MONGO_PASSWORD MONGO_USERNAME \
    RABBITMQ_PASSWORD RABBITMQ_USERNAME RABBITMQ_ERLANG_COOKIE \
    RABBITMQ_DEFAULT_USER RABBITMQ_DEFAULT_PASS \
    SMTP_USERNAME SMTP_PASSWORD SMTP_EMAIL REDIS_PASSWORD; do
    if [ -n "${!key:-}" ]; then
      export "${key}=$(_strip_control_chars "${!key}")"
    fi
  done
}

_create_secret() {
  local name="$1"
  local dest="$2"
  shift 2

  local args=()
  while [ "$#" -gt 0 ]; do
    local literal_key="$1"
    local env_var="$2"
    shift 2
    local value="${!env_var:-}"
    if [ -n "$value" ]; then
      args+=(--from-literal="${literal_key}=${value}")
    fi
  done

  if [ "${#args[@]}" -eq 0 ]; then
    echo "ERROR: No values provided for secret ${name}"
    exit 1
  fi

  kubectl create secret generic "${name}" \
    --namespace="${K8S_NAMESPACE}" \
    "${args[@]}" \
    --dry-run=client -o yaml > "${dest}"
}

_sanitize_secret_env

export POSTGRES_URI="${POSTGRES_URI:-postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}}"

mkdir -p "${SECRETS_DIR}"

_create_secret jwt-secret "${SECRETS_DIR}/jwt-secret.yaml" \
  JWT_SECRET JWT_SECRET \
  JWT_PRIVATE_KEY JWT_PRIVATE_KEY \
  JWT_PUBLIC_KEY JWT_PUBLIC_KEY \
  JWT_ACTIVE_KID JWT_ACTIVE_KID \
  JWT_ISSUER JWT_ISSUER \
  JWT_AUDIENCE JWT_AUDIENCE \
  JWT_ALGORITHM JWT_ALGORITHM \
  JWT_ACCESS_TOKEN_EXPIRES_MINUTES JWT_ACCESS_TOKEN_EXPIRES_MINUTES \
  JWT_REFRESH_TOKEN_EXPIRES_DAYS JWT_REFRESH_TOKEN_EXPIRES_DAYS \
  JWT_REFRESH_TOKEN_SECRET JWT_REFRESH_TOKEN_SECRET \
  JWT_SESSION_SECRET JWT_SESSION_SECRET \
  JWT_EXPIRATION_MINUTES JWT_EXPIRATION_MINUTES

_create_secret auth-secret "${SECRETS_DIR}/auth-secret.yaml" \
  JWT_SECRET JWT_SECRET \
  JWT_PRIVATE_KEY JWT_PRIVATE_KEY \
  JWT_PUBLIC_KEY JWT_PUBLIC_KEY \
  JWT_ACTIVE_KID JWT_ACTIVE_KID \
  JWT_ISSUER JWT_ISSUER \
  JWT_AUDIENCE JWT_AUDIENCE \
  JWT_ALGORITHM JWT_ALGORITHM \
  JWT_ACCESS_TOKEN_EXPIRES_MINUTES JWT_ACCESS_TOKEN_EXPIRES_MINUTES \
  JWT_REFRESH_TOKEN_EXPIRES_DAYS JWT_REFRESH_TOKEN_EXPIRES_DAYS \
  JWT_REFRESH_TOKEN_SECRET JWT_REFRESH_TOKEN_SECRET \
  JWT_SESSION_SECRET JWT_SESSION_SECRET \
  POSTGRES_USER POSTGRES_USER \
  POSTGRES_PASSWORD POSTGRES_PASSWORD \
  POSTGRES_DB POSTGRES_DB \
  POSTGRES_HOST POSTGRES_HOST \
  POSTGRES_PORT POSTGRES_PORT \
  POSTGRES_SSL_MODE POSTGRES_SSL_MODE \
  POSTGRES_URI POSTGRES_URI

_create_secret gateway-secret "${SECRETS_DIR}/gateway-secret.yaml" \
  RABBITMQ_USERNAME RABBITMQ_USERNAME \
  RABBITMQ_PASSWORD RABBITMQ_PASSWORD \
  RABBITMQ_HOST RABBITMQ_HOST \
  RABBITMQ_PORT RABBITMQ_PORT \
  RABBITMQ_EXCHANGE RABBITMQ_EXCHANGE \
  VIDEO_UPLOAD_QUEUE VIDEO_UPLOAD_QUEUE \
  NOTIFICATION_QUEUE NOTIFICATION_QUEUE \
  GATEWAY_EVENTS_QUEUE GATEWAY_EVENTS_QUEUE \
  JWT_SECRET JWT_SECRET

_create_secret rabbitmq-secret "${SECRETS_DIR}/rabbitmq-secret.yaml" \
  RABBITMQ_DEFAULT_USER RABBITMQ_DEFAULT_USER \
  RABBITMQ_DEFAULT_PASS RABBITMQ_DEFAULT_PASS \
  RABBITMQ_USERNAME RABBITMQ_USERNAME \
  RABBITMQ_PASSWORD RABBITMQ_PASSWORD \
  RABBITMQ_ERLANG_COOKIE RABBITMQ_ERLANG_COOKIE \
  RABBITMQ_AMQP_URL RABBITMQ_AMQP_URL \
  RABBITMQ_URI RABBITMQ_URI

_create_secret mongodb-secret "${SECRETS_DIR}/mongodb-secret.yaml" \
  MONGO_HOST MONGO_HOST \
  MONGO_PORT MONGO_PORT \
  MONGO_DATABASE MONGO_DATABASE \
  MONGO_USERNAME MONGO_USERNAME \
  MONGO_PASSWORD MONGO_PASSWORD \
  MONGO_AUTH_SOURCE MONGO_AUTH_SOURCE \
  MONGO_URI MONGO_URI

_create_secret postgres-secret "${SECRETS_DIR}/postgres-secret.yaml" \
  POSTGRES_HOST POSTGRES_HOST \
  POSTGRES_PORT POSTGRES_PORT \
  POSTGRES_DB POSTGRES_DB \
  POSTGRES_USER POSTGRES_USER \
  POSTGRES_PASSWORD POSTGRES_PASSWORD \
  POSTGRES_SSL_MODE POSTGRES_SSL_MODE \
  POSTGRES_URI POSTGRES_URI \
  POSTGRES_POOL_SIZE POSTGRES_POOL_SIZE \
  POSTGRES_MAX_OVERFLOW POSTGRES_MAX_OVERFLOW \
  POSTGRES_POOL_TIMEOUT POSTGRES_POOL_TIMEOUT \
  POSTGRES_POOL_RECYCLE POSTGRES_POOL_RECYCLE \
  POSTGRES_CONNECT_TIMEOUT POSTGRES_CONNECT_TIMEOUT \
  POSTGRES_READ_HOST POSTGRES_READ_HOST \
  POSTGRES_READ_PORT POSTGRES_READ_PORT \
  POSTGRES_BACKUP_BUCKET POSTGRES_BACKUP_BUCKET \
  POSTGRES_BACKUP_PREFIX POSTGRES_BACKUP_PREFIX

_create_secret notification-secret "${SECRETS_DIR}/notification-secret.yaml" \
  SMTP_USERNAME SMTP_USERNAME \
  SMTP_PASSWORD SMTP_PASSWORD \
  SMTP_EMAIL SMTP_EMAIL \
  JWT_SECRET JWT_SECRET

_create_secret redis-secret "${SECRETS_DIR}/redis-secret.yaml" \
  REDIS_PASSWORD REDIS_PASSWORD

echo "Rendered Kubernetes secrets to ${SECRETS_DIR}"
