loopback_users.guest = true
management.load_definitions = /etc/rabbitmq/definitions.json
listeners.tcp.default = 5672
management.tcp.port = 15672
vm_memory_high_watermark.relative = 0.6
disk_free_limit.relative = 1.0
heartbeat = 600
log.console = true
log.console.level = info
