apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: "{{ .Values.postgresql.auth.username | default "postgres" }}"
  POSTGRES_PASSWORD: "{{ required "POSTGRES_PASSWORD must be set" .Values.postgresql.auth.password }}"
  POSTGRES_DB: "{{ .Values.postgresql.auth.database | default "video_to_audio_converter" }}"
  POSTGRES_HOST: "{{ .Values.postgresql.host | default "postgres" }}"
  POSTGRES_PORT: "{{ .Values.service.port | default "5432" }}"
  POSTGRES_SSL_MODE: "{{ .Values.postgresql.sslMode | default "prefer" }}"
  POSTGRES_URI: "postgresql://{{ .Values.postgresql.auth.username | default "postgres" }}:{{ required "POSTGRES_PASSWORD must be set" .Values.postgresql.auth.password }}@{{ .Values.postgresql.host | default "postgres" }}:{{ .Values.service.port | default "5432" }}/{{ .Values.postgresql.auth.database | default "video_to_audio_converter" }}?sslmode={{ .Values.postgresql.sslMode | default "prefer" }}"
