apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql

  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 5432

  type: {{ .Values.service.type }}