name: Helm Validation

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:

  helm-validate:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

      - name: Helm Template Validation
        run: |
          find infrastructure/helm -name Chart.yaml -exec dirname {} \; | while read chart
          do
            helm template "$chart" > /dev/null
          done
