name: Reusable Docker Build Workflow

on:
  workflow_call:

    inputs:

      docker_compose_file:
        required: false
        type: string
        default: docker-compose.yml

    secrets:

      DOCKER_PASSWORD:
        required: true

jobs:

  reusable-docker-build:

    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Verify Required Credentials
        env:
          DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          test -n "${DOCKER_USERNAME}"
          test -n "${DOCKER_PASSWORD}"

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Docker Login
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Validate Docker Compose File
        run: |
          docker compose -f "${{ inputs.docker_compose_file }}" config

      - name: Build Docker Images
        run: |
          docker compose -f "${{ inputs.docker_compose_file }}" build

      - name: Push Docker Images
        run: |
          docker compose -f "${{ inputs.docker_compose_file }}" push
