name: Reusable Security Workflow

on:
  workflow_call:

jobs:

  reusable-security-scan:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.26.0
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: security/trivy/trivy.yaml
          trivyignores: security/trivy/ignore.yaml
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@0.26.0
        with:
          scan-type: config
          scan-ref: infrastructure/
          trivy-config: security/trivy/trivy.yaml
          trivyignores: security/trivy/ignore.yaml
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Install Gitleaks
        run: |
          GITLEAKS_VERSION=v8.18.0
          wget -q https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_linux_x64.tar.gz
          tar -xzf gitleaks_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: gitleaks detect --source . --verbose
