name: Security Pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:

  trivy-fs-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          trivy-config: security/trivy/trivy.yaml
          trivyignores: security/trivy/ignore.yaml
          format: sarif
          output: security/trivy/reports/trivy-fs.sarif
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Upload Trivy FS SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: security/trivy/reports/trivy-fs.sarif
          category: trivy-filesystem

  trivy-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: config
          scan-ref: infrastructure/
          trivy-config: security/trivy/trivy.yaml
          trivyignores: security/trivy/ignore.yaml
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

  trivy-image-scan:
    runs-on: ubuntu-latest
    needs: [trivy-fs-scan]

    strategy:
      matrix:
        service: [gateway, auth, converter, notification]

    steps:
      - uses: actions/checkout@v4

      - name: Build service image
        run: docker build -t scan-${{ matrix.service }}:ci ./services/${{ matrix.service }}

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: image
          image-ref: scan-${{ matrix.service }}:ci
          trivy-config: security/trivy/trivy.yaml
          trivyignores: security/trivy/ignore.yaml
          format: sarif
          output: security/trivy/reports/trivy-${{ matrix.service }}.sarif
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH

      - name: Upload Trivy Image SARIF
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: security/trivy/reports/trivy-${{ matrix.service }}.sarif
          category: trivy-image-${{ matrix.service }}

  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Gitleaks
        run: |
          GITLEAKS_VERSION=v8.18.0
          wget -q https://github.com/gitleaks/gitleaks/releases/download/${GITLEAKS_VERSION}/gitleaks_linux_x64.tar.gz
          tar -xzf gitleaks_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks
        run: gitleaks detect --source . --verbose
