name: Terraform Validation

on:

  pull_request:

  push:
    branches:
      - main

permissions:
  contents: read

jobs:

  terraform:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: infrastructure/terraform

    steps:

      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Format Check
        run: terraform fmt -recursive -check

      - name: Terraform Validate
        run: terraform validate
